config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" } 

  resources :articles
  resources :albumes do
    member do
      get 'like', to: "albumes#like"
      get 'unlike', to: "albumes#unlike"
    end
  end
  match '/albumes/:id/add' => 'albumes#add_picture', via: [:get, :post], as: :album_picture 
  root to: "home#index" 
  get 'users' => 'home#all_users', as: :users
  get 'users/:id' => 'home#show', via: :get,as: :show_user
  get '/pictures' => 'albumes#pictures', as: :users_pictures   
  get '/my_favourite' => 'albumes#favourite', as: :favourites
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def all_users
    @users = User.all
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/all_users.html.erb
<table class="table">
  
    <th> No </th>
    <th> Email </th>
  <% @users.each_with_index do |user, index| %>
    <tr>    
      <td><%=index+1 %></td>
      <td><%= user.email%></td>
       <td><%= image_tag user.image,:width => 50 %>
      <td><%#= link_to 'edit', edit_user_registration_url(user) %></td>
      <td><%#= link_to 'Destroy', user_registration_path(user.id), :confirm => 'Are you sure you want to destroy your account?', :method => :delete %></td>
      <td><%#= link_to 'show', show_user_path(user.id) %></td>
    </tr>
<% end %>
</table>

app/views/home/show.html.erb
<p>
  <b>Name:</b>
  <%= @user.email %>
</p>

<%= image_tag @user.image(:medium) %>

<br />

<%#= link_to 'Edit', edit_landscape_path(@landscape) %> |
<%#= link_to 'Back', landscapes_path %>