config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" } 

  resources :articles
  resources :albumes do
    member do
      get 'like', to: "albumes#like"
      get 'unlike', to: "albumes#unlike"
    end
  end
  match '/albumes/:id/add' => 'albumes#add_picture', via: [:get, :post], as: :album_picture 
  root to: "home#index" 
  get 'users' => 'home#all_users', as: :users
  get 'users/:id' => 'home#show', via: :get,as: :show_user
  get '/pictures' => 'albumes#pictures', as: :users_pictures   
  get '/my_favourite' => 'albumes#favourite', as: :favourites
end

app/controllers/albumes_controller.rb
class AlbumesController < ApplicationController
  
  def new
    @album = Album.new
  end

  def create
    albumes = Album.create(album_params)
    if albumes.save
      flash[:success] = Settings.section.notice.album.create
      redirect_to albumes_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def show
    album = Album.find_by_id(params[:id])
    @pictures = album.pictures
  end

  def index 
    @albumes = Album.all
  end

  def add_picture
    if params[:authenticity_token].present?
      picture = Picture.create(:image => params[:picture][:image], :album_id => params[:id])
      if picture.save
       redirect_to users_pictures_path
        # respond_to do |format|
        #   format.js{ picture.js.erb }
        # end
      else
        render :back  
      end
    end
  end

  def like
    picture = Picture.find_by_id(params[:id])
    album = picture.album

    if current_user.likes picture
      album.update_attributes(:total_count => album.total_count.to_i + 1)
      redirect_to users_pictures_path
    end
  end

  def unlike
    picture = Picture.find_by_id(params[:id])
    album = picture.album

    if current_user.dislikes picture
      album.update_attributes(:total_count => album.total_count.to_i - 1)
      redirect_to users_pictures_path
    end
  end

  def pictures
    @pictures = Picture.paginate(:page => params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def favourite
    # a = Array.new
    # albumes = Album.all
    # albumes.each do |alb|
    #   alb.pictures.each do | picture | 
    #     @i = a.push(picture.get_likes.count) 
    #   end
   

    # @pictures = Album.first.pictures
    #   @pictures.each do |t| 
    #     @i = a.push(t.get_likes.count) 
    #   end
  end

private
  def album_params
    params.require(:album).permit( :name, :user_id )
  end
end

app/helpers/albumes_helper.rb
module AlbumesHelper
end

app/views/albumes/_form.html.erb
<%= form_for @album, :url => { :action => :create, :controller=>'albumes' } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.submit %>
<% end %>

app/views/albumes/_pictures.html.erb
<% @pictures.each do |picture| %>
  <div style="float:left; margin: 0 8px 20px 0;">
    <%= image_tag picture.image, :size => "250x200", :class => "pic" %> 

    <p>
      <% if !current_user.voted_up_on? picture %>
        <%= link_to image_tag("like.png",title: 'like', :width => '50px'), like_albume_path(picture), :remote => true %>  
      <% else %>
        <%= link_to image_tag("dislike12.png", title: 'unlike', :width => '50px'), unlike_albume_path(picture), :remote => true %>  
      <% end %>
      <% if picture.get_likes.size > 0 %>
        <% if picture.get_likes.size == 1 && current_user %>
            <span>You like this</span>
        <% else %>
          <span><b title = "<%= voter_names(picture) %>" ><%= picture.get_likes.size %></b> People likes this</span>
        <% end %>  
      <% end %>
    </p>
  </div>
<% end %>
<%= will_paginate @pictures %>  

app/views/albumes/_show.html.erb
<% @pictures.each do | album_picture |%>
 <div style="float:left; margin: 0 8px 20px 0;">
 <%= image_tag album_picture.image, :size => "250x200", :class => "pic" %>
  <p>
      <% if !current_user.voted_up_on? album_picture %>
        <%= link_to image_tag("like.png",title: 'like', :width => '50px'), like_albume_path(album_picture), :remote => true %>  
      <% else %>
        <%= link_to image_tag("dislike12.png", title: 'unlike', :width => '50px'), unlike_albume_path(album_picture), :remote => true %>  
      <% end %>
     <% if album_picture.get_likes.size > 0 %>
        <% if album_picture.get_likes.size.eql?(1) && current_user.voted_up_on?(album_picture) %>
            <span>You like this</span>
        <% else %>
          <span><b title = "<%= voter_names(album_picture) %>" ><%= album_picture.get_likes.size %></b> People likes this</span>
        <% end %>  
      <% end %>
    </p>
  </div>
<% end %> 

app/views/albumes/add_picture.html.erb
<%= form_for Picture.new, :url => album_picture_path, :html => {:method => :post} do |f| %>
  <%= f.label :image %>
  <span class="btn btn-default btn-file">
   <%= f.file_field :image %>
  </span>
  <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.submit :class => 'btn' %>
<% end %>

app/views/albumes/favourite.html.erb
<%#=@i.inject(0){|sum,x| sum + x }%>

app/views/albumes/index.html.erb
<h2><b>Popular Album </b></h2> 
  <%= link_to 'Add Album', new_albume_path, :class => 'btn' %>
<table class="table">
  <th> No </th>
  <th> Name </th>
  <% @albumes.each_with_index do | album, index | %>
    <tr>
      <td><%= index+1 %></td>
      <% if album.pictures.first.present?   %>
        <td><%= link_to image_tag(album.pictures.first.image,:width => '100px'),albume_path(album) %></td>
      <% else %>
        <td><%= link_to image_tag('default.jpg',:width=> '100px',:height => '70px'), albume_path(album)%></td>
      <% end %>
      <% if  current_user.albums.pluck(:name).include?(album.name)  %>
        <td><%= link_to 'Add photo', album_picture_path(album), :class => 'btn' %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/albumes/new.html.erb
<%= render 'form' %>

app/views/albumes/pictures.html.erb
<div class = "picture_pagination">
  <%= render 'pictures' %>
</div>

app/views/albumes/pictures.js.erb
$('.picture_pagination').html("<%= escape_javascript(render("pictures"))%>")
$('.album_pictures').html("<%= escape_javascript(render("show"))%>")

app/views/albumes/show.html.erb
<div class = "album_pictures">
  <%= render 'show' %>
</div>