config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" } 

  resources :articles
  resources :albumes do
    member do
      get 'like', to: "albumes#like"
      get 'unlike', to: "albumes#unlike"
    end
  end
  match '/albumes/:id/add' => 'albumes#add_picture', via: [:get, :post], as: :album_picture 
  root to: "home#index" 
  get 'users' => 'home#all_users', as: :users
  get 'users/:id' => 'home#show', via: :get,as: :show_user
  get '/pictures' => 'albumes#pictures', as: :users_pictures   
  get '/my_favourite' => 'albumes#favourite', as: :favourites
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Demo", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
          <% if user_signed_in? %>  
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Article', articles_path %>
          <li><%= link_to 'Album', albumes_path %>
          <li><%= link_to 'Picture', users_pictures_path %>
          <li><%#= link_to 'favourite', favourites_path %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">User<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile",edit_user_registration_path, :method => :get %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out" ,destroy_user_session_path, :method => :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log in",  new_user_session_path %></li>
        <% end %>       
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<html>
<head>
  <title>FriendsCircle</title>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'custom' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
   <div class="container">
   <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%#= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>